const body = document.querySelector('body');
const header = document.createElement('div');
const blockFixed = document.createElement('div');
const companyHead = document.createElement('div');
const companyLink = document.createElement('a');
const companyType = document.createElement('div');
const companyName = document.createElement('div');
const companyServices = document.createElement('div');
const blockMenu = document.createElement('ul');
const listIndex = document.createElement('li');
const listAbout = document.createElement('li');
const listProducts = document.createElement('li');
const listServices = document.createElement('li');
const listContacts = document.createElement('li');
const index = document.createElement('a');
const about = document.createElement('a');
const products = document.createElement('a');
const services = document.createElement('a');
const contacts = document.createElement('a');
const blockHiddenSmall = document.createElement('div');
const blockHiddenBig = document.createElement('div');

blockFixed.classList.add('BLOCK_FIXED');
companyHead.classList.add('UPPER_HEAD', 'TEXT_WHITE');
companyLink.classList.add('MENU_BUTTON');
companyLink.href = 'index.html';
companyType.innerHTML = 'Открытое акционерное общество';
companyName.innerHTML = '"ПРОМПЕЧАТЬ"';
companyServices.innerHTML = 'полиграфические услуги';
companyName.classList.add('TEXT_GIGANTIC', 'TEXT_BOLD');
blockMenu.classList.add('MENU', 'TEXT_WHITE');
listIndex.classList.add('MENU_POINT', 'TEXT_BOLD', 'TEXT_BIG');
listAbout.classList.add('MENU_POINT', 'TEXT_BOLD', 'TEXT_BIG');
listProducts.classList.add('MENU_POINT', 'TEXT_BOLD', 'TEXT_BIG');
listServices.classList.add('MENU_POINT', 'TEXT_BOLD', 'TEXT_BIG');
listContacts.classList.add('MENU_POINT', 'TEXT_BOLD', 'TEXT_BIG');
index.classList.add('MENU_BUTTON');
index.href = 'index.html';
index.title = 'Главная страница';
listIndex.innerHTML = 'ГЛАВНАЯ';
about.classList.add('MENU_BUTTON');
about.href = 'about.html';
about.title = 'О нас';
listAbout.innerHTML = 'О НАС';
products.classList.add('MENU_BUTTON');
products.href = 'products.html';
products.title = 'Наша продукция';
listProducts.innerHTML = 'ПРОДУКЦИЯ';
services.classList.add('MENU_BUTTON');
services.href = 'services.html';
services.title = 'Наши услуги';
listServices.innerHTML = 'УСЛУГИ';
contacts.classList.add('MENU_BUTTON');
contacts.href = 'contacts.html';
contacts.title = 'Связаться с нами';
listContacts.innerHTML = 'КОНТАКТЫ';
blockHiddenSmall.classList.add('BLOCK_HIDDEN_SMALL');
blockHiddenBig.classList.add('BLOCK_HIDDEN_BIG');

document.body.appendChild(header);
header.appendChild(blockFixed);
header.appendChild(blockHiddenBig);
blockFixed.appendChild(companyHead);
blockFixed.appendChild(blockMenu);
blockMenu.appendChild(index);
index.appendChild(listIndex);
blockMenu.appendChild(about);
about.appendChild(listAbout);
blockMenu.appendChild(products);
products.appendChild(listProducts);
blockMenu.appendChild(services);
services.appendChild(listServices);
blockMenu.appendChild(contacts);
contacts.appendChild(listContacts);

blockFixed.appendChild(blockHiddenSmall);
companyHead.appendChild(companyLink);
companyLink.appendChild(companyType);
companyLink.appendChild(companyName);
companyLink.appendChild(companyServices);
